sudo: required
services:
  - docker

before_install:
  - docker build -t sa77irak/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myotherproject

script:
  - docker run -e CI=true sa77irak/react-test npm test
  # - docker run myotherproject runmytests

after_success:
  - docker build -t sa77irak/multi-client ./client
  - docker build -t sa77irak/multi-nginx ./nginx
  - docker build -t sa77irak/multi-server ./server
  - docker build -t sa77irak/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sa77irak/multi-client
  - docker push sa77irak/multi-nginx
  - docker push sa77irak/multi-server
  - docker push sa77irak/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-2-245139697380'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
